"""Tests for export_run_md: render shape + key sections."""
from __future__ import annotations

from datetime import UTC, datetime
from uuid import uuid4

from src.schemas import (
    CaseResultRead,
    CategoryStat,
    RunDetail,
    RunStats,
    WorstCase,
)
from src.services.exporter import export_run_md


def _build_run(*, with_errors: bool = False, with_worst: bool = True) -> RunDetail:
    started = datetime(2026, 5, 1, 12, 0, 0, tzinfo=UTC)
    completed = datetime(2026, 5, 1, 12, 3, 30, tzinfo=UTC)
    run_id = uuid4()
    case_results: list[CaseResultRead] = []

    # 4 successful + optional 1 errored
    for i, score in enumerate((5, 4, 3, 2)):
        case_results.append(
            CaseResultRead(
                id=uuid4(),
                run_id=run_id,
                test_case_id=uuid4(),
                agent_prompt_sent=f"SYSTEM:\nyou\n\nUSER:\nq{i}",
                agent_output=f"answer {i}",
                agent_latency_ms=120 + i * 10,
                judge_prompt_sent="judge…",
                judge_score=score,
                judge_reasoning=f"reason {i}",
                judge_latency_ms=80,
                error=None,
                created_at=started,
            ),
        )
    if with_errors:
        case_results.append(
            CaseResultRead(
                id=uuid4(),
                run_id=run_id,
                test_case_id=uuid4(),
                agent_prompt_sent=None,
                agent_output=None,
                agent_latency_ms=None,
                judge_prompt_sent=None,
                judge_score=None,
                judge_reasoning=None,
                judge_latency_ms=None,
                error="HTTPError: timeout",
                created_at=started,
            ),
        )

    successful = [cr for cr in case_results if cr.judge_score is not None]
    pass_rate = sum(1 for cr in successful if (cr.judge_score or 0) >= 4) / len(successful)
    stats = RunStats(
        total_cases=len(case_results),
        successful_cases=len(successful),
        errored_cases=len(case_results) - len(successful),
        pass_rate=pass_rate,
        avg_score=sum(cr.judge_score or 0 for cr in successful) / len(successful),
        score_distribution={
            i: sum(1 for cr in successful if cr.judge_score == i) for i in range(1, 6)
        },
        per_category={
            "refund": CategoryStat(count=2, pass_rate=0.5, avg_score=3.5),
            "qa": CategoryStat(count=2, pass_rate=0.5, avg_score=3.5),
        },
        worst_cases=[
            WorstCase(
                case_result_id=case_results[3].id,
                test_case_id=case_results[3].test_case_id,
                input="why did it fail",
                judge_score=2,
                judge_reasoning="missed the policy",
            ),
        ] if with_worst else [],
    )

    return RunDetail(
        id=run_id,
        test_set_id=uuid4(),
        agent_id=uuid4(),
        agent_version_id=uuid4(),
        agent_version=1,
        judge_model="llama-3.3-70b-versatile",
        status="completed",
        started_at=started,
        completed_at=completed,
        total_cases=len(case_results),
        completed_cases=len(case_results),
        errored_cases=stats.errored_cases,
        error=None,
        test_set_name="SMS Support",
        agent_name="Concise Agent",
        case_results=case_results,
        stats=stats,
        failure_clusters=None,
    )


def test_export_renders_required_sections() -> None:
    md = export_run_md(_build_run())
    assert "# SMS Support × Concise Agent" in md
    assert "## TL;DR" in md
    assert "## Configuration" in md
    assert "## Score distribution" in md
    assert "## Per-category breakdown" in md
    # Footer
    assert "Generated by EvalLab" in md


def test_export_pass_rate_formatted() -> None:
    run = _build_run()
    md = export_run_md(run)
    pct = int(round(run.stats.pass_rate * 100))  # type: ignore[union-attr]
    assert f"**{pct}% pass rate**" in md


def test_export_includes_worst_case_section() -> None:
    md = export_run_md(_build_run())
    assert "need attention" in md.lower()
    assert "missed the policy" in md  # judge reasoning surfaces


def test_export_errors_section_only_when_errors() -> None:
    md_no_err = export_run_md(_build_run(with_errors=False))
    assert "## Errors" not in md_no_err

    md_err = export_run_md(_build_run(with_errors=True))
    assert "## Errors (1)" in md_err
    assert "HTTPError: timeout" in md_err


def test_export_handles_incomplete_run() -> None:
    """A RunDetail with stats=None is truncated to a one-liner, not crashed."""
    started = datetime(2026, 5, 1, 12, 0, 0, tzinfo=UTC)
    incomplete = RunDetail(
        id=uuid4(),
        test_set_id=uuid4(),
        agent_id=uuid4(),
        agent_version_id=None,
        agent_version=None,
        judge_model="x",
        status="running",
        started_at=started,
        completed_at=None,
        total_cases=10,
        completed_cases=3,
        errored_cases=0,
        error=None,
        test_set_name="ts",
        agent_name="a",
        case_results=[],
        stats=None,
        failure_clusters=None,
    )
    md = export_run_md(incomplete)
    assert "not completed yet" in md
